# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 218e425d8fa293677043307d6503b6a70b52dde6bc63bae28b9b5afeb701d05172c9d9597c79f70e99dbe07d67ddc57b1074afe7665f96f1ca29953506d9b1d8

test:
  secret_key_base: a5661fe2b713be10612e4d619bb05eba7e407a0758d3e8e7c86f982f4f9767cae4f64e8f081bd3ce62918eb54c462c89556c7f3badc807498bbbc89bca47b577

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
